In [0]:
from __future__ import print_function, division
import pylab as pl
import pandas as pd
import numpy as np
import scipy.stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from numpy import inf
import re

%pylab inline

Populating the interactive namespace from numpy and matplotlib

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

In [0]:
df = pd.read_csv("2016weather_update.csv", encoding=('utf-8'))

In [0]:
df.head()
df.shape

(10382, 16)

In [0]:
df["Date"] = pd.to_datetime(df["Date"])

In [0]:
#df["Time (EST)"] = df["Time (EST)"])

In [0]:
#df = df[pd.to_datetime(df["Time (EST)"]).dt.minute==51]
#df.head()

In [0]:
#df.shape

In [0]:
df["Temp."].isnull().values.any()

False

In [0]:
df_relevant = df[['Date','Temp.','Humidity','Conditions',"Time (EST)"]].copy()
#df1231.columns = ['Temperature', 'Humidity', 'Conditions']
df_relevant.rename(columns={'Temp.': 'Temperature',"Time (EST)":'Time'}, inplace=True)
df_relevant.head()

        Date Temperature Humidity Conditions      Time
0 2016-01-01     42.1 °F      51%   Overcast  12:51 AM
1 2016-01-01     41.0 °F      53%   Overcast   1:51 AM
2 2016-01-01     41.0 °F      55%   Overcast   2:51 AM
3 2016-01-01     41.0 °F      55%   Overcast   3:51 AM
4 2016-01-01     39.9 °F      58%   Overcast   4:51 AM

In [0]:
#dfrelevant_mean['Temperature'] = dfrelevant_mean['Temperature'].str.split('°').str[0]
pattern = re.compile(r'([\d.]*).*')
def extract_beginning_number(a):
    match = pattern.match(a)
    if match:
        return match.group(1)
    else:
        return np.nan
df_relevant['Temperature'] = pd.to_numeric(df_relevant['Temperature'].apply(extract_beginning_number))
df_relevant['Humidity'] = pd.to_numeric(df_relevant['Humidity'].apply(extract_beginning_number))
# dfrelevant_mean['Temperature'] = dfrelevant_mean['Temperature'].str.split('Â').str[0]
#dfrelevant_mean['Temperature'] = dfrelevant_mean["Temperature"].str.strip(" ")
df_relevant.head()

        Date  Temperature  Humidity Conditions      Time
0 2016-01-01         42.1      51.0   Overcast  12:51 AM
1 2016-01-01         41.0      53.0   Overcast   1:51 AM
2 2016-01-01         41.0      55.0   Overcast   2:51 AM
3 2016-01-01         41.0      55.0   Overcast   3:51 AM
4 2016-01-01         39.9      58.0   Overcast   4:51 AM

In [0]:
conditions_list = df_relevant.Conditions.unique()
def aggregate_4hour(group):
    dt_total = group.dt.sum()
    conditions = {
        con: np.dot(group.Conditions == con, group.dt) / dt_total
        for con in conditions_list
    }
    return pd.Series(dict(
        Date=group.index.min().date(),
        Temperature=np.dot(group.Temperature, group.dt) / dt_total,
        Humidity=np.dot(group.Humidity, group.dt) / dt_total,
        **conditions
    ))

df_relevant.index = pd.to_datetime((
    df_relevant.Date.dt.strftime('%m-%d-%Y') + " " + pd.to_datetime(df_relevant.Time).dt.strftime('%H:%M:%S')))
df_relevant['dt'] = np.append(np.diff(df_relevant.index)/np.timedelta64(1,'h'), 1.)
df_updated = df_relevant.groupby(pd.TimeGrouper(freq = '4H')).apply(aggregate_4hour)
df_updated['TIMEINT'] = ((df_updated.index.hour/4)+1).astype(int)
df_updated.head()

,Clear,Date,Fog,Haze,Heavy Rain,Heavy Snow,Humidity,Light Freezing Fog,Light Freezing Rain,Light Rain,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Snow,Temperature,Unknown,TIMEINT
2016-01-01 00:00:00,0.00,2016-01-01,0.0,0.0,0.0,0.0,53.50,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,41.275,0.0,1
2016-01-01 04:00:00,0.00,2016-01-01,0.0,0.0,0.0,0.0,58.25,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,39.450,0.0,2
2016-01-01 08:00:00,0.00,2016-01-01,0.0,0.0,0.0,0.0,53.50,0.0,0.0,0.0,0.0,0.0,0.75,0.25,0.0,0.0,0.0,39.675,0.0,3
2016-01-01 12:00:00,0.00,2016-01-01,0.0,0.0,0.0,0.0,49.25,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,39.450,0.0,4
2016-01-01 16:00:00,0.75,2016-01-01,0.0,0.0,0.0,0.0,48.50,0.0,0.0,0.0,0.0,0.0,0.00,0.25,0.0,0.0,0.0,37.450,0.0,5

In [0]:
df_updated.to_csv('weather_combined.csv',encoding='utf-8')

In [0]:
df_weather = pd.read_csv("weather_combined _updated.csv")
df_weather["Date"] = pd.to_datetime(df["Date"])
df_weather.head()

,Date,TIMEINT,Temperature,Humidity,Heavy Rain,Heavy Snow,Light Freezing Fog,Light Freezing Rain,Light Rain,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Snow,Haze,Fog,Clear
0,2016-01-01,1,41.275,53.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00
1,2016-01-01,2,39.450,58.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00
2,2016-01-01,3,39.675,53.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.75,0.25,0.0,0.0,0.0,0.0,0.0,0.00
3,2016-01-01,4,39.450,49.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00
4,2016-01-01,5,37.450,48.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,0.0,0.0,0.0,0.0,0.0,0.75

In [0]:
df_mta = pd.read_csv("mta_combined.csv")
df_mta["Date"] = pd.to_datetime(df_mta["DATE"])
df_mta = df_mta[["STATION","Date","TIMEINT","ENTRIES"]].copy()
df_mta.head()

  STATION       Date  TIMEINT     ENTRIES
0    1 AV 2016-01-01        1  1407774726
1    1 AV 2016-01-01        2  1407775796
2    1 AV 2016-01-01        3  1407776768
3    1 AV 2016-01-01        4  1407779799
4    1 AV 2016-01-01        5  1407783611

In [0]:
df_final= df_mta.merge(df_weather, on = ["Date","TIMEINT"], how = 'inner')
df_final

,STATION,Date,TIMEINT,ENTRIES,Temperature,Humidity,Heavy Rain,Heavy Snow,Light Freezing Fog,Light Freezing Rain,...,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Snow,Haze,Fog,Clear
0,1 AV,2016-01-01,1,1407774726,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
1,1 AV,2016-01-01,1,1407774726,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
2,1 AV,2016-01-01,1,1407774726,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
3,1 AV,2016-01-01,1,1407774726,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
4,103 ST,2016-01-01,1,124276833,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
5,103 ST,2016-01-01,1,124276833,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
6,103 ST,2016-01-01,1,124276833,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
7,103 ST,2016-01-01,1,124276833,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
8,103 ST-CORONA,2016-01-01,1,61101554,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
9,103 ST-CORONA,2016-01-01,1,61101554,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
10,103 ST-CORONA,2016-01-01,1,61101554,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
11,103 ST-CORONA,2016-01-01,1,61101554,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
12,104 ST,2016-01-01,1,3861195697,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
13,104 ST,2016-01-01,1,3861195697,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
14,104 ST,2016-01-01,1,3861195697,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
15,104 ST,2016-01-01,1,3861195697,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
16,110 ST,2016-01-01,1,25164897,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
17,110 ST,2016-01-01,1,25164897,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
18,110 ST,2016-01-01,1,25164897,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
19,110 ST,2016-01-01,1,25164897,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
20,111 ST,2016-01-01,1,110712424,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
21,111 ST,2016-01-01,1,110712424,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
22,111 ST,2016-01-01,1,110712424,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
23,111 ST,2016-01-01,1,110712424,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
24,116 ST,2016-01-01,1,1709330711,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
25,116 ST,2016-01-01,1,1709330711,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
26,116 ST,2016-01-01,1,1709330711,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
27,116 ST,2016-01-01,1,1709330711,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
28,116 ST-COLUMBIA,2016-01-01,1,1209304607,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
29,116 ST-COLUMBIA,2016-01-01,1,1209304607,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762035,VAN SICLEN AVE,2016-03-16,6,13396304,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762036,VAN SICLEN AVE,2016-03-16,6,13396304,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762037,VAN SICLEN AVE,2016-03-16,6,13396304,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762038,W 4 ST-WASH SQ,2016-03-16,6,804654480,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762039,W 4 ST-WASH SQ,2016-03-16,6,804654480,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762040,W 4 ST-WASH SQ,2016-03-16,6,804654480,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762041,WAKEFIELD/241,2016-03-16,6,16348575,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762042,WAKEFIELD/241,2016-03-16,6,16348575,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762043,WAKEFIELD/241,2016-03-16,6,16348575,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762044,WALL ST,2016-03-16,6,534194483,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762045,WALL ST,2016-03-16,6,534194483,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762046,WALL ST,2016-03-16,6,534194483,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762047,WEST FARMS SQ,2016-03-16,6,438530467,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762048,WEST FARMS SQ,2016-03-16,6,438530467,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762049,WEST FARMS SQ,2016-03-16,6,438530467,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762050,WHITEHALL S-FRY,2016-03-16,6,266199476,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762051,WHITEHALL S-FRY,2016-03-16,6,266199476,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762052,WHITEHALL S-FRY,2016-03-16,6,266199476,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762053,WINTHROP ST,2016-03-16,6,31797792,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762054,WINTHROP ST,2016-03-16,6,31797792,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762055,WINTHROP ST,2016-03-16,6,31797792,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762056,WOODHAVEN BLVD,2016-03-16,6,56147736,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762057,WOODHAVEN BLVD,2016-03-16,6,56147736,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762058,WOODHAVEN BLVD,2016-03-16,6,56147736,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762059,YORK ST,2016-03-16,6,31874236,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762060,YORK ST,2016-03-16,6,31874236,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762061,YORK ST,2016-03-16,6,31874236,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762062,ZEREGA AV,2016-03-16,6,53633504,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762063,ZEREGA AV,2016-03-16,6,53633504,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762064,ZEREGA AV,2016-03-16,6,53633504,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75

In [0]:
df_final.to_csv('final_dataset.csv',encoding='utf-8')

In [0]:
df_f = pd.read_csv('final_dataset.csv')
df_f.head()

,Unnamed: 0,STATION,Date,TIMEINT,ENTRIES,Temperature,Humidity,Heavy Rain,Heavy Snow,Light Freezing Fog,...,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Snow,Haze,Fog,Clear
0,0,1 AV,2016-01-01,1,1407774726,41.275,53.5,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00
1,1,1 AV,2016-01-01,1,1407774726,34.000,48.5,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.75
2,2,1 AV,2016-01-01,1,1407774726,35.775,52.5,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,1.00
3,3,1 AV,2016-01-01,1,1407774726,35.275,55.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.0,0.0,0.0,0.0,0.00
4,4,103 ST,2016-01-01,1,124276833,41.275,53.5,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00

In [0]:
df_f.drop(["Unnamed: 0"],axis =1)

,STATION,Date,TIMEINT,ENTRIES,Temperature,Humidity,Heavy Rain,Heavy Snow,Light Freezing Fog,Light Freezing Rain,...,Light Snow,Mostly Cloudy,Overcast,Partly Cloudy,Rain,Scattered Clouds,Snow,Haze,Fog,Clear
0,1 AV,2016-01-01,1,1407774726,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
1,1 AV,2016-01-01,1,1407774726,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
2,1 AV,2016-01-01,1,1407774726,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
3,1 AV,2016-01-01,1,1407774726,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
4,103 ST,2016-01-01,1,124276833,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
5,103 ST,2016-01-01,1,124276833,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
6,103 ST,2016-01-01,1,124276833,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
7,103 ST,2016-01-01,1,124276833,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
8,103 ST-CORONA,2016-01-01,1,61101554,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
9,103 ST-CORONA,2016-01-01,1,61101554,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
10,103 ST-CORONA,2016-01-01,1,61101554,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
11,103 ST-CORONA,2016-01-01,1,61101554,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
12,104 ST,2016-01-01,1,3861195697,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
13,104 ST,2016-01-01,1,3861195697,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
14,104 ST,2016-01-01,1,3861195697,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
15,104 ST,2016-01-01,1,3861195697,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
16,110 ST,2016-01-01,1,25164897,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
17,110 ST,2016-01-01,1,25164897,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
18,110 ST,2016-01-01,1,25164897,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
19,110 ST,2016-01-01,1,25164897,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
20,111 ST,2016-01-01,1,110712424,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
21,111 ST,2016-01-01,1,110712424,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
22,111 ST,2016-01-01,1,110712424,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
23,111 ST,2016-01-01,1,110712424,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
24,116 ST,2016-01-01,1,1709330711,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
25,116 ST,2016-01-01,1,1709330711,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
26,116 ST,2016-01-01,1,1709330711,35.775,52.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,1.00
27,116 ST,2016-01-01,1,1709330711,35.275,55.00,0.0,0.0,0.0,0.0,...,0.0,0.00,0.75,0.25,0.0,0.00,0.0,0.0,0.0,0.00
28,116 ST-COLUMBIA,2016-01-01,1,1209304607,41.275,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.00
29,116 ST-COLUMBIA,2016-01-01,1,1209304607,34.000,48.50,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762035,VAN SICLEN AVE,2016-03-16,6,13396304,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762036,VAN SICLEN AVE,2016-03-16,6,13396304,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762037,VAN SICLEN AVE,2016-03-16,6,13396304,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762038,W 4 ST-WASH SQ,2016-03-16,6,804654480,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762039,W 4 ST-WASH SQ,2016-03-16,6,804654480,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762040,W 4 ST-WASH SQ,2016-03-16,6,804654480,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762041,WAKEFIELD/241,2016-03-16,6,16348575,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762042,WAKEFIELD/241,2016-03-16,6,16348575,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762043,WAKEFIELD/241,2016-03-16,6,16348575,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762044,WALL ST,2016-03-16,6,534194483,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762045,WALL ST,2016-03-16,6,534194483,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762046,WALL ST,2016-03-16,6,534194483,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762047,WEST FARMS SQ,2016-03-16,6,438530467,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762048,WEST FARMS SQ,2016-03-16,6,438530467,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762049,WEST FARMS SQ,2016-03-16,6,438530467,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762050,WHITEHALL S-FRY,2016-03-16,6,266199476,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762051,WHITEHALL S-FRY,2016-03-16,6,266199476,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762052,WHITEHALL S-FRY,2016-03-16,6,266199476,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762053,WINTHROP ST,2016-03-16,6,31797792,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762054,WINTHROP ST,2016-03-16,6,31797792,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762055,WINTHROP ST,2016-03-16,6,31797792,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762056,WOODHAVEN BLVD,2016-03-16,6,56147736,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762057,WOODHAVEN BLVD,2016-03-16,6,56147736,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762058,WOODHAVEN BLVD,2016-03-16,6,56147736,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762059,YORK ST,2016-03-16,6,31874236,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762060,YORK ST,2016-03-16,6,31874236,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762061,YORK ST,2016-03-16,6,31874236,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75
762062,ZEREGA AV,2016-03-16,6,53633504,34.825,53.50,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.0,0.25,0.0,0.0,0.0,0.75
762063,ZEREGA AV,2016-03-16,6,53633504,38.400,65.25,0.0,0.0,0.0,0.0,...,0.0,0.25,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.50
762064,ZEREGA AV,2016-03-16,6,53633504,34.325,55.75,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.25,0.0,0.00,0.0,0.0,0.0,0.75

In [0]:
# df_relevant.Conditions.unique()

In [0]:
#dfrelevant_dummy = pd.get_dummies(df_relevant.Conditions,prefix='',prefix_sep='')
#dfrelevant_dummy.head()

In [0]:
#dfrelevant_dummy = dfrelevant_dummy.groupby(np.arange(len(dfrelevant_dummy))//4).sum()

In [0]:
#dfrelevant_dummy.head()

In [0]:
#print(dfrelevant_dummy.shape)
#df_relevant_4throw = df_relevant[df_relevant.index % 4 == 0] 
#df_relevant_4throw.head()

In [0]:
#df_relevant_4throw= df_relevant_4throw.reset_index()

In [0]:
#df_relevant_date = df_relevant_4throw.drop(['Temperature','Humidity','Conditions'], axis = 1)
#df_relevant_date.head()

In [0]:
# df_relevant_date.shape

In [0]:
# dfrelevant_mean = df_relevant.drop(['Conditions','Date'], axis = 1)
# dfrelevant_mean.head()

In [0]:
# np.diff(df_relevant.time)

In [0]:
#dfrelevant_mean['Temperature'] = pd.Series(dfrelevant_mean['Temperature']).convert_objects(convert_numeric=True)
#dfrelevant_mean['Humidity'] = pd.Series(dfrelevant_mean['Humidity']).convert_objects(convert_numeric=True)

In [0]:
# dfrelevant_mean['Temperature']= pd.to_numeric(dfrelevant_mean['Temperature'], errors='coerce')
# dfrelevant_mean['Humidity']= pd.to_numeric(dfrelevant_mean['Humidity'], errors='coerce')

In [0]:
# dfrelevant_mean

In [0]:
# dfrelevant_mean.shape

In [0]:
# dfrelevant_mean = dfrelevant_mean.groupby(np.arange(len(dfrelevant_mean))//4).mean()

In [0]:
# dfrelevant_mean.head()